# Generated by Django 3.0.3 on 2020-04-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='patreon',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Show email publicly?'),
        ),
        migrations.AddField(
            model_name='user',
            name='steam',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
