# Generated by Django 3.0.3 on 2020-04-22 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200422_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patreon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='steam',
        ),
    ]
