# Generated by Django 2.1.7 on 2019-08-09 03:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='basepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_tags', to='page.BasePage'),
        ),
        migrations.AddField(
            model_name='pagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_pagetag_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='page.PageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
