# Generated by Django 3.0 on 2020-04-16 22:50

from django.db import migrations
import django.forms.widgets
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_blogpage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('Rich_Text', wagtail.core.blocks.RichTextBlock()), ('Podcast', wagtail.core.blocks.StructBlock([('podcast', wagtail.snippets.blocks.SnippetChooserBlock('podcast.Podcast'))], icon='fa-headphones')), ('Review_Info', wagtail.core.blocks.StructBlock([('game', wagtail.snippets.blocks.SnippetChooserBlock('game.Game'))], icon='fa-pencil')), ('Author_Bio', wagtail.core.blocks.StructBlock([('user', wagtail.core.blocks.ChooserBlock(target_model='users.User', widget=django.forms.widgets.Select))], icon='fa-user'))], blank=True),
        ),
    ]
