# Generated by Django 3.0.3 on 2020-04-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_blogfolder_folder_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogfolder',
            old_name='folder_icon',
            new_name='icon',
        ),
    ]
