# Generated by Django 3.0.3 on 2020-05-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20200501_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='legacy_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
