# Generated by Django 3.0.3 on 2020-05-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_blogpage_header_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFolder',
            fields=[
                ('blogfolder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.BlogFolder')),
            ],
            options={
                'abstract': False,
            },
            bases=('page.blogfolder',),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
