# Generated by Django 3.0.3 on 2020-05-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('page', '0019_auto_20200505_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfolder',
            name='show_in_sidebar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagfolder',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taggit.Tag'),
        ),
    ]
