# Generated by Django 3.0.3 on 2020-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_auto_20200505_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='show_in_sidebar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='show_in_sidebar',
            field=models.BooleanField(default=False),
        ),
    ]
