# Generated by Django 3.0.3 on 2020-05-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_auto_20200505_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='enable_comments',
            field=models.BooleanField(default=False),
        ),
    ]
