# Generated by Django 3.0.3 on 2020-05-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_auto_20200506_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
    ]
