# Generated by Django 3.0.3 on 2020-08-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('stream', 'Twitch Stream'), ('online', 'Virtual Game Night'), ('meatspace', 'In-Person Event'), ('convention', 'Convention'), ('other', 'Other')], default='online', max_length=30),
        ),
    ]
