# Generated by Django 3.0.3 on 2020-08-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
    ]
