# Generated by Django 3.0.3 on 2020-05-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_type'),
        ('image', '0002_customimage_image_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.Game'),
        ),
    ]
