# Generated by Django 2.1.11 on 2019-09-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_podcastsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastsettings',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
