# Generated by Django 2.1.11 on 2019-09-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_podcastsettings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='episode_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
