# Generated by Django 2.1.11 on 2019-09-08 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('podcast', '0004_auto_20190908_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcast_file', to='wagtailmedia.Media'),
        ),
    ]
