# Generated by Django 2.1.11 on 2019-09-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_podcast_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
