# Generated by Django 2.1.11 on 2019-12-01 07:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='format',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='number_of_players',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='play_time',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherinfo',
            name='game',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_info', to='game.Game'),
        ),
    ]
