# Generated by Django 2.1.11 on 2019-12-01 08:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20191201_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField()),
                ('redeemed', models.BooleanField()),
                ('game', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_codes', to='game.Game')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
