# Generated by Django 2.1.11 on 2019-12-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_reviewcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcodes',
            name='redeemed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
