# Generated by Django 2.1.11 on 2019-12-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('game', '0004_reviewcodes_redeemed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='box_art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='image.CustomImage'),
        ),
        migrations.AlterField(
            model_name='reviewcodes',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcodes',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
