# Generated by Django 2.1.11 on 2019-12-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20191201_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcodes',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcodes',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
