# Generated by Django 3.0.3 on 2020-05-02 18:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('game', '0009_auto_20200502_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_tags', to='game.Game')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_gametag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='game.GameTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
