# Generated by Django 3.0.3 on 2020-05-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('video-game', 'Video Game'), ('tabletop-game', 'Tabletop'), ('book', 'Book')], default='video-game', max_length=30),
        ),
    ]
