# Generated by Django 3.0.3 on 2020-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20200506_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcopy',
            name='notes',
            field=models.TextField(blank=True, help_text='What version of the game? Is this DLC? An expansion? Who gave it to us?'),
        ),
    ]
