# Generated by Django 3.0.3 on 2020-05-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spritesanddice', '0003_sidebarsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SidebarSettings',
        ),
    ]
